### ISSUE TITLE
Restore ErrorMailer

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#66] opened 2012-06-22 18:55 UTC
The administrative user should get email notification in case of special events, like failure to get PIDs from Fedora.  This functionality existed in Tracksys2 and should be restored.

**Comment by louffoster** [comment] 2018-01-09 21:03
duplicate of [https://github.com/uvalib/tracksys/issues/116](https://github.com/uvalib/tracksys/issues/116)

**Closed by louffoster** 2018-01-09 21:03 UTC
