### ISSUE TITLE
More easily create units within orders

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#12] opened 2012-02-22 21:00 UTC
While in the show view of a Unit, Spec Coll public services staff want to create additional units within the same order.  Want to avoid an extra click to go up to order and then hit 'New Unit'.

**Comment by louffoster** [comment] 2018-01-09 19:01
this is a duplicate of another issue. A similar feature was added in version 5.6.0

**Closed by louffoster** 2018-01-09 19:01 UTC
Labels: Patron Portal, User Interface
